security:
    encoders:
        OAuth2\ServerBundle\Entity\User:
                    algorithm:          sha1
                    encode_as_base64:   false
                    iterations:         1

    providers:
        database_users:
            entity: { class: AppBundle:User }
        oauth2:
            id: oauth2.user_provider

    firewalls:
        main:
            pattern: ^/api
            anonymous: true

        oauth_token:
            pattern: ^/oauth/token
            anonymous: true


    access_control:
        - { path: ^/_wdt|_profiler, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }




